// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqusOrBANjq5-sN1IPB2OWTFweN_SViMs',
    appId: '1:317622863603:web:12252165a6bdfbf94b5986',
    messagingSenderId: '317622863603',
    projectId: 'jiranjigyo-d8ce8',
    authDomain: 'jiranjigyo-d8ce8.firebaseapp.com',
    storageBucket: 'jiranjigyo-d8ce8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwSDdCsfHIs7Ry64Gvb4wEdH9XH3tq31M',
    appId: '1:317622863603:android:c97ac0a1d79fbebd4b5986',
    messagingSenderId: '317622863603',
    projectId: 'jiranjigyo-d8ce8',
    storageBucket: 'jiranjigyo-d8ce8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeiz5kazsaXyv_memQ0B_a4qoK17Rs7Co',
    appId: '1:317622863603:ios:32086f0d0219f01b4b5986',
    messagingSenderId: '317622863603',
    projectId: 'jiranjigyo-d8ce8',
    storageBucket: 'jiranjigyo-d8ce8.appspot.com',
    iosClientId: '317622863603-g99bkh4mcbd7pd66jp2lqo5mmv9gu3cd.apps.googleusercontent.com',
    iosBundleId: 'com.example.jiranjigyo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeiz5kazsaXyv_memQ0B_a4qoK17Rs7Co',
    appId: '1:317622863603:ios:32086f0d0219f01b4b5986',
    messagingSenderId: '317622863603',
    projectId: 'jiranjigyo-d8ce8',
    storageBucket: 'jiranjigyo-d8ce8.appspot.com',
    iosClientId: '317622863603-g99bkh4mcbd7pd66jp2lqo5mmv9gu3cd.apps.googleusercontent.com',
    iosBundleId: 'com.example.jiranjigyo',
  );
}
